### ISSUE TITLE
Scapy_Exception: No /dev/bpf handle is available !

### ISSUE THREAD

**Issue by Non808** [secdev/scapy#1015]
(First day on Github (mainly to leave this comment) so not totally sure of the etiquette sorry)

I am trying to send an icmp thing with a message attached after watching [this](https://www.youtube.com/watch?v=K-V478AsQWg) YouTube tutorial (cause I thought it would be fun). 

So downloaded scapy ran it followed the video to the letter at first it worked fine, but I had some (unrelated) issue capturing the packets with Wireshark I couldn't entirely tell that it had worked. So I decided to run the `send(icmp)` command quite a few times to see whether I could see it. It worked for quite some time (as I was still having trouble finding the packets), but then at some arbitrary point it stopped working and when I typed `send(icmp)` it gave me this error:
`Traceback (most recent call last):`
`  File "<console>", line 1, in <module>`
`  File "scapy/sendrecv.py", line 290, in send`
`    socket = conf.L3socket(*args, **kargs)`
`   File "scapy/arch/bpf/supersocket.py", line 57, in __init__`
`   (self.ins, self.dev_bpf) = get_dev_bpf()`
`  File "scapy/arch/bpf/core.py", line 98, in get_dev_bpf`
`    raise Scapy_Exception("No /dev/bpf handle is available !")`
`Scapy_Exception: No /dev/bpf handle is available !`

I tried this again, and again but it kept giving the same error.

Here is the full two lines I typed in to get this error:
`icmp=IP(src='192.168.1.10',dst='192.168.1.1')/ICMP()/"hello"`          [which works fine]
`send(icmp)`                                                                                          [which raises error]

I had a look around (on google) for anyone else with the same error but couldn't find any.

**Comment by gpotter2** [comment]
Hi !
It seems that you are using an old scapy version :/
Please download the latest dev version from here: https://github.com/secdev/scapy/archive/master.zip
then unzip it and install it with `python setup.py install`
This should fix the bug you're having

**Comment by Non808** [comment]
Thanks for you help @gpotter2, I downloaded the zip, unzipped it ran the command (in the correct place - that one took me way too long to figure out), got a `Permissions` error. 
Then I ran `sudo python setup.py install` then I got a `Operation Not Permitted` error (because I run mac which is more paranoid than Marvin from *Red*). 
So I look around on google and find [this post](https://github.com/cs01/gdbgui/issues/38) which shows someone with the same issue and how they fixed it (I modified their fix a bit, with `sudo --user python setup.py install`) which works but only for a little while when it quickly gives me a slightly different version of `Operation Not Permitted` (I think this one works even less than the last command but could be that they had already installed the other parts). 
Then I realized - halfway through writing this - that I was being an absolute idiot and I should be using `python3 setup.py install` (because my computer is weird like that), that worked perfectly, but before I delete this post and forget about it (I thought to myself), I should test the problem I had in the first place... 

So I type in `scapy` and it runs fine (good sign - means I haven't broken it), type in the original command lines (see first post) then watch a different error come up. This time saying: `struct.error: argument for 's' must be a bytes object`. Then I thought to myself well I know python has a `bytes()` function Ill use that so I create a variable `b = bytes("hello",'utf-8')` that seems to work then redo the other command lines, get the same error. So now my question has changed to how can I fix this error:
`Traceback (most recent call last):`
`  File "<console>", line 1, in <module>`
`  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/scapy/sendrecv.py", line 290, in send`
 `   socket = conf.L3socket(*args, **kargs)`
 ` File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/scapy/arch/bpf/supersocket.py", line 69, in __init__`
 `   fcntl.ioctl(self.ins, BIOCSETIF, struct.pack("16s16x", self.iface))`
`struct.error: argument for 's' must be a bytes object`

Sorry about all this it seems like I've jumped down the rabbit hole from what seemed like a simple YouTube video I could follow to... well this mess.

**Comment by gpotter2** [comment]
I’m really sorry that you had to go through all of this.

We have a patch for this bug, which has not beeen released yet. Please wait for https://github.com/secdev/scapy/pull/861 to be finished and merged, then that kind of problems will be done.

We’re actually finishing Python 3 porting on this build, which means some functions are temporarily broken. It should be working soon

**Comment by gpotter2** [comment]
In the meantime, you can still use the scapy version you have downloaded with Python 2.7 (Python not python3) where all of this is currently working

**Comment by vano144** [comment]
macOs High Sierra 10.13.2 (17C88)
I still have this exception, after sudo pip3 install git+https://github.com/secdev/scapy:

```Traceback (most recent call last):
  File "ping/test.py", line 9, in <module>
    ans, unans = sr(IP(dst=ip)/ICMP())
  File "/Users/vano144/PycharmProjects/ping/venv/lib/python3.6/site-packages/scapy/sendrecv.py", line 364, in sr
    s = conf.L3socket(promisc=promisc, filter=filter, iface=iface, nofilter=nofilter)
  File "/Users/vano144/PycharmProjects/ping/venv/lib/python3.6/site-packages/scapy/arch/bpf/supersocket.py", line 69, in __init__
    fcntl.ioctl(self.ins, BIOCSETIF, struct.pack("16s16x", self.iface))
struct.error: argument for 's' must be a bytes object```

**Comment by gpotter2** [comment]
@guedou Could you have a look ?

**Comment by guedou** [comment]
Issue confirmed.

**Comment by guedou** [comment]
@vano144 could you try PR #1064 ?

**Comment by vano144** [comment]
@guedou, yes it fixes problem, thanks

**Comment by mikiol60** [comment]
It's related to some privilege issue. Try adding  `sudo`
