### ISSUE TITLE
Show() method do not recognize IPv6 address correctly

### ISSUE THREAD

**Issue by kpowojski** [secdev/scapy#579]
Hi,
I've just started using SCAPY to parse my PCAP files with IPv6 traffic. I'm only interested in header part of each packet. At a first look something with **packet.show()** is not correct. This is a part of code I'm using:

```
def main():
   sniff(offline='traffic.pcap', prn=my_method,store=0)


def my_method(packet):
   packet.show()
```

As a result I got: 
![image](https://i.imgur.com/5JTXU1Q.png)

IP src and IP dst are strange. Here is how it looks like in wireshark:
![image](https://i.imgur.com/Hhrr1AI.png)

In my opinion there is something wrong with parsing IPv6 header in show() method.

**Comment by guedou** [comment]
The packet looks weird in wireshark. I doubt that it is a valid IPv6 packet.

Can you try again with Scapy pull from github, and share your pcap ?

**Comment by kpowojski** [comment]
I've just commited the latest scapy version from Github and installed in on my workstation. 
The issue still exists ;(

I attached sample PCAP file to this comment to allow you reproduce the issue.

[test.zip](https://github.com/secdev/scapy/files/876899/test.zip)

**Comment by gpotter2** [comment]
The pcap you provided looks like:
```
>>> a.show()
0000 87.225.55.209 > 0.0.0.0 246 frag:1599 / Padding
0001 87.225.55.209 > 0.0.0.0 246 frag:1599 / Padding
0002 136.46.254.5 > 0.0.0.0 252 frag:1590 / Padding
0003 136.46.32.241 > 0.0.0.0 252 frag:1590 / Padding
>>> a[0]
<IP  version=6 ihl=0 tos=0x80 len=0 id=32 flags= frag=1599 ttl=173 proto=246 chksum=0x6718 src=87.225.55.209 dst=0.0.0.0 options=[<IPOption_EOL  copy_flag=0 optclass=control option=end_of_list |>, <IPOption_EOL  copy_flag=0 optclass=control option=end_of_list |>, <IPOption_EOL  copy_flag=0 optclass=control option=end_of_list |>, <IPOption_EOL  copy_flag=0 optclass=control option=end_of_list |>, <IPOption  copy_flag=1 optclass=1 option=commercial_security length=252 value='\xa7\x81\xa0N\xb0\x0e\x00\x00\x00\x00\x00\x00\x00\x00\x9b\x93\x00P' |>] |<Padding  load='\xcd,\xfe\xf0\xc8\x8c\x82_\x80\x10\x7fN.\xee\x00\x00\x01\x01\x08\n' |>>
[........]
```

Every thing looks normal: The provided packets have a valid IPv4 address... Are you sure that the packet that you have captured using scapy is the same than the one captured in wireshark ?

**Comment by kpowojski** [comment]
Header during starting scapy looks like: 
>INFO: Can't import PyX. Won't be able to use psdump() or pdfdump().
WARNING: No route found for IPv6 destination :: (no default route?)
INFO: Can't import python-cryptography v1.7+. Disabled WEP decryption/encryption.
INFO: Can't import python-cryptography v1.7+. Disabled IPsec encryption/authentication.
INFO: Can't import python-cryptography v1.7+. Disabled PKI & TLS crypto-related features.
Welcome to Scapy (2.3.3.dev347)

I've just opened this file in Wireshark and everything looks like it is IPv6 traffic - try by yourself :)

**Comment by gpotter2** [comment]
I think this is due to
> WARNING: No route found for IPv6 destination :: (no default route?)

What OS + version are you using ? Might be a problem because of that...

**Comment by kpowojski** [comment]
Wireshark on Windows
Scapy on Linux

**Comment by guedou** [comment]
The header indicates that the linktype is 101 (LINKTYPE_RAW). By default, Scapy decodes it as IPv4 and does not check for the IP version.

Thanks for reporting the issue, it is fixed in PR #588.

**Comment by kpowojski** [comment]
In my opinion the issue still exists.

**Comment by guedou** [comment]
Can you explain why ? It works fine with your pcap. I need to modify it before merging it.

**Comment by kpowojski** [comment]
I've just downloaded the repo one again, rebuild everything and `show()` function still does not present right ip addresses. 

Here is my scapy header:
`INFO: Can't import PyX. Won't be able to use psdump() or pdfdump().
WARNING: No route found for IPv6 destination :: (no default route?)
INFO: Can't import python-cryptography v1.7+. Disabled WEP decryption/encryption.
INFO: Can't import python-cryptography v1.7+. Disabled IPsec encryption/authentication.
INFO: Can't import python-cryptography v1.7+. Disabled PKI & TLS crypto-related features.
Welcome to Scapy (2.3.3.dev355)`

**Comment by guedou** [comment]
It is not merged yet. You need to pull the code from the PR to test it.

**Comment by kpowojski** [comment]
Could you tell me how to do this, I'm not as familiar with git ;)

**Comment by gpotter2** [comment]
`git pull upstream pull/579/head`

**Comment by kpowojski** [comment]
IMFO command should be `git pull origin pull/588/head` because the PR request was #588.
