### ISSUE TITLE
Colour escape code messiness with show()

### ISSUE THREAD

**Issue by andysouthwell2** [secdev/scapy#982]
(using latest dev-master)

This used to work fine with the previous scapy I used, 2.3.3. I'm using Windows 7, standard console (I do not have Windows 10 available to check that). If I create a packet and then do show(), I get this:

![image](https://user-images.githubusercontent.com/21983603/33929674-3a1f375a-dfe2-11e7-91d8-4c53f7848265.png)

**Comment by gpotter2** [comment]
Please check that IPython is correctly installed.
Does scapy shows any error/warning while booting ?

**Comment by andysouthwell2** [comment]
Here's what I see - and ipython seems to be present (I can run it)

![image](https://user-images.githubusercontent.com/21983603/33982980-67b4bdd4-e0aa-11e7-9ab7-56fce5cb99a6.png)

**Comment by gpotter2** [comment]
as said in the headline: `trailets not available. Some Scapy shell features won't be available`.
`trailets` is provided automatically with newer versions of IPython

**Comment by guedou** [comment]
@gpotter2 could you add the minimal IPython version requirement in `doc/installation.rst` ?

**Comment by p-l-** [comment]
@gpotter2 @guedou Maybe we should switch `conf.color_theme` to `BlackAndWhite()` (under Windows only? it seems to work fine under Linux) when `traitlets` is not available?

@andysouthwell2 could you upgrade iPython and report if it fixes your problem?

**Comment by guedou** [comment]
If this works, I think that it is a safe default. We only need to add test for this corner case and mock the absence of `trailtets`.

**Comment by gpotter2** [comment]
I’m actually wondering if traitlets reallly fixes IPython, or if it’s just a too old version... waiting for @andysouthwell2 answer :)
Will test that in a week

**Comment by andysouthwell2** [comment]
Sorry, can't test this until the NY as it's on a work laptop, but will look as soon as I can

**Comment by andysouthwell2** [comment]
Hi,

ok, I have have a look now. It's actually proving very difficult to update iPython because of local policies (managing of tool versions and installations across multiple internal teams). We are using Python 2.7.2.5, which includes iPython 2.3.1, and that's not going to change fast. I have attempted to make use of a newer iPython (3.2.3) but our Python 2.7.2.5 didn't seem to like that (setup-tools runtime errors). So I have tried the other Python we have available here, 3.4.1.0, which includes iPython 4.1.2. If I run scapy-master with that, I still see the same errors. Perhaps that iPython is still not new enough? I will talk to our internal team that manages tool versions but this is as far as I can get at the moment I'm afraid - sorry.

I understand that I am not the only person using scapy :-) and other people have their own requirements, but given colourised packets seemed to work fine in the older scapy I used (2.3.1 which is part of our Python 2.7.2.5), which presumably predates the use of iPython, for me, this seems like a backwards step. Of course, you'll say that we should upgrade our tools and it's our own problem for not doing so....that's so easy to argue....but unfortunately for us at least, is not as easy as it sounds.

Anyway.... I have gone as far as I can here. For now, we're going to continue using the old scapy 2.3.1 but we'll hit issues at some point when we need to update to later for some reason.

Feel free to close if you wish

Best Regards
Andy

**Comment by gpotter2** [comment]
@andysouthwell2 I know IPython use the `colorama` library to setup the coloured interface. If you are able to call `import colorama; colorama.init()` before starting scapy it will certainly fix the issue.

If it works, we may also implement that directly in scapy... What do you think @p-l-

**Comment by andysouthwell2** [comment]
@gpotter2 Thanks a lot - that's extremely helpful! That certainly works inasmuch as it fixes the colour issue. I haven't tried this extensively but basic tests seem to work (see screenshot).

Strangely however, I notice there's something odd going on in the [] brackets after the @@In prompt (see the red-coloured circles in the image). Seems very minor but I can't say for sure if there are further problems elsewhere beyond what I've tried. Any thoughts?

If that's the only side-effect then I think it'd be good to have this fix - it's definitely better to have the colour-coding of the packet data. But it really needs more testing, to be more sure, doesn't it? Can you think of any particular things I can quickly run here to help verify if the problem is confined to just this, or more widespread?

![image](https://user-images.githubusercontent.com/21983603/34515064-596ca1f6-f068-11e7-96f0-0cd414e11873.png)

**Comment by gpotter2** [comment]
@andysouthwell2 Would it be possible for you to install `traitlets` ? On my Windows machine, using IPython 2.3.1, it works after having installed it.

Scapy actually does not even try to setup colors when `traitlets` is not available. It is useally provided directly by newer IPython versions, but it might work if you install it manualy. If you're able to install it, the `colorama` trick should not be needed anymore.

You may try using the #1020 PR, which was required in my case, to see if, with `traitlets` this bug get fixed.

**Comment by andysouthwell2** [comment]
Hi, thanks for those suggestions but no-go I'm afraid. After doing pip install traitlets, I now have traitlets-4.3.2 but now I get this when running scapy:

Traceback (most recent call last):
  File "C:\u-blox\gallery\activestate\python\win\2.7.2.5\Scripts\\scapy", line 25, in <module>
    interact()
  File "c:\Users\andy\Downloads\scapy-master\scapy-master\scapy\main.py", line 524, in interact
    user_ns=SESSION)
TypeError: __init__() got an unexpected keyword argument 'hist_file'

Presumably this traitlets version isn't compatible with Python 2.7.2.5 but if not, I have no clue why pip has decided to install that version. I am not a Python expert but I'd have thought it'd be a bit more intelligent than that? Someone, somewhere is making assumptions about my brain-dead Python install, I guess (scapy or traitlets).

For my own needs I'm happy using the previous workaround you provided me with - I do not personally have any need to progress the problems with this antique Python version further at the moment. If there is anything further you would like me to test though, do let me know. Perhaps a different version of traitlets? I wouldn't know where to start with choosing one, however.

Best Regards
Andy

**Comment by gpotter2** [comment]
The error you are having is fixed in #1020 !
This is a nice start

**Comment by andysouthwell2** [comment]
ok, that's cool - but sadly I don't see how to pull that fix. All I can see is the master branch (which I have done a git pull on), that hasn't been updated for 11 days. It looks like you've added the fix to a personal branch but I am unsure how to reference that and pull it (I have tried but in vain). I am not a regular github user, and not git either for that matter. Sorry - I don't want to burden you. If you can explain how to git-pull the appropriate revision please, I'll give it a go to confirm.

**Comment by gpotter2** [comment]
You should be able to download it in https://codeload.github.com/gpotter2/scapy/zip/ipython-old

**Comment by andysouthwell2** [comment]
Hi, no luck I'm afraid. Thanks for the zip, which I've tried. Now, when I try to pip install traitlets, I just get a bunch of "requirement already satisfied" warnings (traitlets already exists in my python 2.7.2.5). When I run scapy, I still see the original error (colour escape codes printed out to screen)

**Comment by gpotter2** [comment]
FTR this was fixed in https://github.com/secdev/scapy/pull/1169 rather than https://github.com/secdev/scapy/pull/1020
